servingEngineSpec:
  runtimeClassName: ""
  modelSpec:
  - name: "qwen2"
    repository: "vllm/vllm-openai"
    tag: "latest"
    modelURL: "Qwen/Qwen2-7B"
    replicaCount: 1

    requestCPU: 4
    requestMemory: "25Gi"
    requestGPU: 1

    pvcStorage: "50Gi"
    pvcAccessMode:
      - ReadWriteOnce
    pvcMatchLabels:
      model: "qwen2-pv"

    vllmConfig:
      dtype: "float16"
