servingEngineSpec:
  modelSpec:

  # basic
  - name: "opt125m"
    repository: "lmcache/vllm-openai"
    tag: "latest"
    modelURL: "facebook/opt-125m"

    replicaCount: 1

    requestCPU: 2
    requestMemory: "10Gi"
    requestGPU: 1

    pvcStorage: "10Gi"


  # # with pv
  # - name: "opt125m-with-pv"
  #   repository: "lmcache/vllm-openai"
  #   tag: "latest"
  #   modelURL: "facebook/opt-125m"

  #   replicaCount: 1

  #   requestCPU: 2
  #   requestMemory: "10Gi"
  #   requestGPU: 1

  #   pvcStorage: "20Gi"
  #   pvcMatchLabels:
  #     model: "opt-125m"


  # # with LMCache
  # - name: "opt125m"
  #   repository: "lmcache/vllm-openai"
  #   tag: "latest"
  #   modelURL: "facebook/opt-125m"

  #   replicaCount: 1

  #   requestCPU: 2
  #   requestMemory: "25Gi"
  #   requestGPU: 1

  #   pvcStorage: "10Gi"

  #   lmcacheConfig:
  #     enabled: true
  #     cpuOffloadingBufferSize: "10"


  # secondary
  - name: "gpt2"
    repository: "vllm-cpu-env"
    tag: "latest"
    modelURL: "openai-community/gpt2"

    replicaCount: 1

    requestCPU: 2
    requestMemory: "10Gi"
    requestGPU: 0

    pvcStorage: "10Gi"
